title = 'BlenderDMX'
baseURL = 'https://blenderdmx.eu'
languageCode = 'en-us'
enableEmoji = true
summaryLength = 30

[params]
docsUrl = "https://github.com/open-stage/blender-dmx-web"
description = "Blender addon to design and render DMX lighting"


[frontmatter]
date = ['publishDate', 'date', 'lastmod']
expiryDate = ['expiryDate']
lastmod = [':git', 'lastmod', 'date', 'publishDate']
publishDate = ['publishDate', 'date']

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    ordered = false

[module]
  [[module.mounts]]
  source = "assets"
  target = "assets"

  [[module.mounts]]
  source = "node_modules/"
  target = "assets/node_modules"

  [[module.mounts]]
  source = "static"
  target = "static"

  [[module.mounts]]
  source = "node_modules/@fortawesome/fontawesome-free/webfonts"
  target = "static/assets/fonts/fontawesome"
