title = 'BlenderDMX'
baseURL = 'https://blenderdmx.eu'
languageCode = 'en-us'

[frontmatter]
date = ['publishDate', 'date', 'lastmod']
expiryDate = ['expiryDate']
lastmod = [':git', 'lastmod', 'date', 'publishDate']
publishDate = ['publishDate', 'date']

[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
tabWidth = 4
noClasses = true
style  = "nord"

[module]
  [[module.mounts]]
  source = "assets"
  target = "assets"

  [[module.mounts]]
  source = "node_modules/"
  target = "assets/node_modules"

  [[module.mounts]]
  source = "static"
  target = "static"

  [[module.mounts]]
  source = "node_modules/@fortawesome/fontawesome-free/webfonts"
  target = "static/assets/fonts/fontawesome"
